const API_BASE = "http://localhost:8080";

const logoutBtn = document.getElementById("logoutBtn");
const welcomeMsg = document.getElementById("welcomeMsg");

// Reservation creation elements
const guestName = document.getElementById("guestName");
const address = document.getElementById("address");
const contact = document.getElementById("contact");
const roomType = document.getElementById("roomType");
const checkIn = document.getElementById("checkIn");
const checkOut = document.getElementById("checkOut");
const createBtn = document.getElementById("createBtn");
const createMessage = document.getElementById("createMessage");

// Reservation view elements
const resIdInput = document.getElementById("resId");
const viewBtn = document.getElementById("viewBtn");
const reservationDetails = document.getElementById("reservationDetails");

// Show staff name from sessionStorage
const username = sessionStorage.getItem("username") || "Staff";
welcomeMsg.textContent = `Welcome, ${username}`;

// Logout
logoutBtn.addEventListener("click", () => {
  sessionStorage.clear();
  window.location.href = "index2.html";
});

// Helper for calculating total price
const roomRates = { Standard: 8000, Deluxe: 9000, Superior: 12500 };
function calculateTotal(room_type, check_in, check_out) {
  const checkInDate = new Date(check_in);
  const checkOutDate = new Date(check_out);
  const nights = Math.max(
    1,
    Math.ceil((checkOutDate - checkInDate) / (1000 * 60 * 60 * 24)),
  );
  return (roomRates[room_type] || 0) * nights;
}

// Create Reservation
createBtn.addEventListener("click", async () => {
  const payload = {
    guest_name: guestName.value.trim(),
    guest_address: address.value.trim(),
    contact_number: contact.value.trim(),
    room_type: roomType.value,
    check_in: checkIn.value,
    check_out: checkOut.value,
  };

  if (
    !payload.guest_name ||
    !payload.contact_number ||
    !payload.room_type ||
    !payload.check_in ||
    !payload.check_out
  ) {
    createMessage.style.color = "red";
    createMessage.textContent = "Please fill all required fields.";
    return;
  }

  if (new Date(payload.check_out) <= new Date(payload.check_in)) {
    createMessage.style.color = "red";
    createMessage.textContent = "Check-out must be after check-in date.";
    return;
  }

  try {
    const res = await fetch(`${API_BASE}/api/reservation`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    const data = await res.json();

    if (res.ok) {
      createMessage.style.color = "green";
      createMessage.textContent = `Reservation Created! ID: ${data.reservation_id || "generated by server"}`;
      guestName.value = address.value = contact.value = "";
      roomType.value = "";
      checkIn.value = checkOut.value = "";
      resIdInput.value = "";
      viewBtn.click(); // Refresh reservations
    } else {
      createMessage.style.color = "red";
      createMessage.textContent =
        data.message || "Failed to create reservation";
    }
  } catch (err) {
    createMessage.style.color = "red";
    createMessage.textContent = "Error: " + err.message;
  }
});

// View Reservation / All Reservations
viewBtn.addEventListener("click", async () => {
  const resId = resIdInput.value.trim();

  try {
    const res = await fetch(`${API_BASE}/api/reservation`);
    const reservations = await res.json();

    if (!res.ok || !Array.isArray(reservations) || reservations.length === 0) {
      reservationDetails.innerHTML =
        "<p style='color:red'>No reservations found</p>";
      return;
    }

    let html = "";

    const filtered = resId
      ? reservations.filter((r) => String(r.reservation_id) === resId)
      : reservations;

    if (filtered.length === 0) {
      reservationDetails.innerHTML =
        "<p style='color:red'>Reservation not found</p>";
      return;
    }

    filtered.forEach((r) => {
      const totalPrice =
        r.total_price || calculateTotal(r.room_type, r.check_in, r.check_out);
      html += `
        <div class="reservation-card" style="border:1px solid #ccc; padding:10px; margin-bottom:10px; border-radius:5px;">
          <strong>Reservation #${r.reservation_id}</strong><br>
          Guest: ${r.guest_name}<br>
          Contact: ${r.contact_number}<br>
          Address: ${r.guest_address || "—"}<br>
          Room Type: ${r.room_type}<br>
          Check-in: ${r.check_in}<br>
          Check-out: ${r.check_out}<br>
          Total Price: Rs ${totalPrice}<br>
          <button class="generateBillBtn" data-id="${r.reservation_id}" data-total="Rs ${totalPrice}">Generate Bill</button>
        </div>
      `;
    });

    reservationDetails.innerHTML = html;

    // Attach PDF generation
    initGenerateBill();
  } catch (err) {
    reservationDetails.innerHTML =
      "<p style='color:red'>Error: " + err.message + "</p>";
  }
});

// Load all reservations on page load
window.addEventListener("DOMContentLoaded", () => {
  viewBtn.click();
});
